config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do 
    resources :doses
  end 
  root to: 'cocktails#index'
  get '/learn', to: 'cocktails#learn'
  get '/test', to: 'cocktails#test'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :doses
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses
    validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :learn]

  def test

    @cocktails = Cocktail.all.order(:id)
    @result = "Liste de tous les cocktails"
    render 'test'
  end

  def index


    


    
  
    if params[:query].present?
    
        param = params[:query]
        sql = "ingredients.name ilike '%#{param}%' or cocktails.name ilike '%#{param}%'"
        @cocktails = Cocktail.joins(:ingredients).where(sql).distinct()
        @result = "Liste des cocktails avec : #{param} "
    else
       @cocktails = Cocktail.all.order(:id)
       @result = "Liste de tous les cocktails"
    end

    if params[:get]
      if params[:get][:ig]

        list = []
        params[:get][:ig].each { |id| list << id.to_i if id != "" }
        array_name = []
        list.each { |id| array_name << Ingredient.find(id).name }


        # # on cherche tout les cocktails qui on élément qui n'est pas dans la liste 
        # # pour chaque élement dans la liste on test si il n'est pas dans les doses
        # sql = "doses.ingredient_id = #{list[0]} "

        # list.each do |id|
        #   sql += "or doses.ingredient_id != #{id} "
       
        # end

        @all = Cocktail.all
        @cocktails = []


        

        @all.each do |item|
          
          dosage = []

          item.ingredients.each do |x|
            dosage << x.id
          end
          
          if dosage.count > 0

       

            
            if in_list?(dosage, list)

              
              @cocktails << item 

            end
          end
          

          
        end

     


        @result = "Liste des cocktails trouvés"
        @result = "Vous n'avez pas assez d'ingrédients pour faire un cocktail 😢" if @cocktails.count == 0
        #@sql = sql
     
       
        end

    end



  end

  def in_list?(dosage, list) #test un des ingrédient de la liste n'est pas dans les dosages
    dosage.each do |item| #test si tout les element font parti de la liste
      puts "#{list} << #{item} #{list.include? item}" 
      
      unless list.include? item
        return false #pas dans la liste
      end
    end
    return true
  end

  

  # query /cocktails/1
  # GET /cocktails/1.json
  def show
  
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def learn 
    card_list = []
    7.times { card_list << Cocktail.all.sample }
    @cards = card_list
  end 

  private

    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    def cocktail_params
      params.require(:cocktail).permit(:name, :photo, :description)
    end

   
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
    before_action :find_dose, only: [ :show, :destroy, :edit, :update]
    def index
    end
  
    def new
      @dose = Dose.new
      @cocktail = Cocktail.find(params[:cocktail_id])
    end
  
    def edit
    end
  
    def create
      @dose = Dose.new(dose_params)
      @dose.save!
      @cocktail = Cocktail.find(params[:cocktail_id])
  
      redirect_to cocktail_path(@cocktail)
    end
  
    def update
    end
  
    def destroy
      @dose.destroy
      @cocktail = Cocktail.find(params[:cocktail_id])
      redirect_to cocktail_path(@cocktail)
  
    end
  
    def show
    end
  
     private
  
    def find_dose
      @dose = Dose.find(params[:id])
  
    end
  
    def dose_params
      paramsC = {cocktail_id: params[:cocktail_id]}
      params.require(:dose).permit(:description, :ingredient_id).merge(paramsC)
  
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<div data-collapse="medium" data-animation="default" data-duration="400" class="nav-bar w-nav">
<div class="navigation-wrap">
  <a href="#" class="logo-link-2 w-nav-brand">
    <div class="text-block-10"><strong class="bold-text-5"> </strong>Grecocktail</div>
  </a>
  <div class="menu-2">
    <nav role="navigation" class="navigation-items w-nav-menu"><a href="/learn" class="navigation-item-2 w-nav-link">Learn</a><a href="#" class="navigation-item-2 w-nav-link">Mon frigo</a><a href="#" class="navigation-item-2 w-nav-link">All</a></nav>
    <div class="menu-button w-nav-button">
    <img src="<%= image_path "menu-icon_1menu-icon.png" %>"  width="22" alt="menu icon" class="menu-icon"></div>
  </div>
  <a href="mailto:mail@business.com?subject=You&#x27;ve%20got%20mail!" class="button cc-contact-us w-inline-block">
    <div>Connexion</div>
  </a>
</div>
</div>
<div class="menu-box"><a href="#" class="menu-item w-button frigo-btn"><strong></strong> </a><a href="#" class="menu-item active w-button"><strong></strong></a><a href="#" class="menu-item w-button"><strong></strong></a></div>
<div class="banner">
<div class="container w-container">
  <div class="h1">Become a cocktail&#x27;s <strong class="bold-text-4">Master</strong></div>
  <div class="subtitle"><a href="#" class="action w-button">Connexion</a></div>
</div>
</div>
<div class="container-3 w-container">
<div class="div-block-5"><a href="#" class="action w-button frigo-btn">Rechercher avec mes ingrédients</a></div>
<div class="search-box">
  <div class="form-block w-form">
  <%= form_tag cocktails_path, class: "w-100", method: :get do %>
    <%= text_field_tag :query,
    params[:query], class: "search-field", placeholder: "Rechercher"%>
    <button type="submit" class="search-button"><i class="fa fa-search"> </i></button>
  <% end %>
    <div class="w-form-done">
      <div>Thank you! Your submission has been received!</div>
    </div>
    <div class="w-form-fail">
      <div>Oops! Something went wrong while submitting the form.</div>
    </div>
  </div>
</div>
<div class="result">
  <div class="text-block-3">Liste des cocktails</div><a href="#" data-w-id="0d74062c-e2c4-fd4b-0c0d-58fcde32905e" class="add-btn w-button"><strong class="bold-text"></strong></a></div>
<div class="w-layout-grid grid">


  <% @cocktails.each do |item| %>
   
    <div id=<%="card_"+item.id.to_s%> class="cocktail-card" style="background-image : linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),  url( <%= item.photo.present? ? item.photo : cl_image_path("vucs2ncsgrk6eo0iho2g") %>); background-size: cover;">

      <div class="card-cocktail-header">
      <div class="text-block-7">100%</div>
      <a href="#" class="button-2 w-button"><strong></strong></a></div>
      <div class="card-inner-cocktail">
        <div class="text-block-2" style="height: 80%"><%= item.name %></div>
      </div>
      <div class="card-footer hidden"></div>
    </div>


    <div id=<%="modal_"+item.id.to_s%> class="modal">
<div class="modal-header"><a data-w-id="c9b0a6de-14b6-d1c7-bce1-8201d9bb9d3e" href="#" class="close w-button"></a></div>
<div class="modal-inner">
  <div class="colone">
    <div class="cocktail-card show" style="background-image : linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),  url( <%= item.photo.present? ? item.photo : cl_image_path("vucs2ncsgrk6eo0iho2g") %>); background-size: cover;">
      <div class="card-cocktail-header"><a href="#" class="button-2 w-button"><strong></strong></a></div>
      <div class="card-inner-cocktail">
        <div class="text-block-2"><%=item.name%></div>
      </div>
      <div class="card-footer"></div>
    </div>
    <div class="card _100">
      <div class="card-header">
        <div class="text-block-4">Ingrédients</div>
      </div>
      <div class="card-inner">

       <% item.doses.each do |item| %>
          <div class="ig-list">
            <div class="text-block-6"><%= item.description%></div>
            <div class="text-block-5"></div>
          </div>
        <%end%>
    
      </div>
    </div>
  </div>
  <div class="card description">
    <div class="card-header">
      <div class="text-block-4">Description</div>
    </div>
    <div class="card-inner-cocktail">
    <%= simple_format(item.description) %>
    <br></div>
  </div>
</div>
</div>

  <%end%>


 


</div>
</div>

<div id="modal_frigo" class="modal frigo">
<div class="modal-header">
  <div class="text-block-9">Mes ingrédients</div><a data-w-id="59a80e03-2a8c-50bb-a8de-08fce2e057de" href="#" class="close w-button"></a></div>
<div class="modal-inner">
  <div class="colone">
    <div class="card _100">
      <div class="container-selector">
      <%= form_tag cocktails_path, method: :get do %>
        <%= select('get', :ig , Ingredient.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, class: 'select2', multiple: 'multiple', data: { placeholder: "Ajouter un ingrédient" }) %>
        <hr>
        <div class="container-submit">
        <%= submit_tag "Recherche", class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
</div>

app/views/cocktails/learn.html.erb
<div class="view">


<div class="show-view">
  <div class="progress">
    <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
  </div>


  <% @cards.each do |item| %>

  <div class="column-1 hidden">
    <div class="card-cocktail" style='background-image:linear-gradient(rgba(100,100,100,0.3), rgba(100,100,100,0.4)),url("<%= item.photo %>")'>
    <%= item.name %>
    </div>

    <div class="dosages card" id=card-<%=item.id%>>
      <h2>Liste des ingredients </h2>
      <p>
        <% item.doses.each do |item|%>
          <div class="ig-list hidden"><%= item.description %> </div>
        <% end %>
      </p>
    </div>
  </div>

  <div class="column-2 hidden">
    <div class="answer card">
      <h2>Quelle sont les ingrédients de ce cockails (<%= item.name %> ) ?</h2>
      <div class="content">
        <div class="container-answer">
            <div class="btn-show">Voir la réponse</div>
            <div class="btn-yes hidden">Je sais </div>
            <div class="btn-no hidden">Je sais pas</div>
        </div>
      </div>
    </div>
  </div>

  <%end%>

</div>
</div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<div class="view">

  <div class="show-view">
    <div class="column-1">
      <div class="card-cocktail" style='background-image:linear-gradient(rgba(100,100,100,0.3), rgba(100,100,100,0.4)),url("<%= @cocktail.photo %>")'>
      <%= @cocktail.name %>
    </div>

      <div class="dosages card">
        <h2>Liste des ingredients 
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal">
            +
          </button>
        </h2>
        <p>
          <% @cocktail.doses.each do |item|%>
            <div class="ig-list"><%= item.description %> 
            <%= link_to  icon('fas', 'trash-alt') , @cocktail.id.to_s+'/doses/'+item.id.to_s, method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
          <% end %>
          
        </p>
      </div>
    </div>

    <div class="column-2">
      <div class="description card">
        <h2>Description
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#edit-description-modal">
        edit
      </button>
        </h2>
        <p>
          <%= simple_format(@cocktail.description) %>
        </p>
      </div>
    </div>

  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ajouter un ingrédient</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@cocktail, Dose.new] do |f| %>
          <%= f.input :description, placeholder: 'dosage + ingrédient ex : 2cl lait de coco' %>
          <%= f.association :ingredient %>
          <%= f.submit "Ajouter", class: "btn btn-primary" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="edit-description-modal" tabindex="-1" role="dialog" aria-labelledby="edit-description-modal-Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="edit-description-modal-Label">Description</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>w
      <div class="modal-body">
        <%= simple_form_for @cocktail do |f| %>
          <%= f.input :description, as: :text, :input_html => {:rows => 15}, placeholder: 'Etape 1 :' %>
          <%= f.submit "Ajouter", class: "btn btn-primary" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/cocktails/test.html.erb
<div data-collapse="medium" data-animation="default" data-duration="400" class="nav-bar w-nav">
<div class="navigation-wrap">
  <a href="#" class="logo-link-2 w-nav-brand">
    <div class="text-block-10"><strong class="bold-text-5"> </strong>Grecocktail</div>
  </a>
  <div class="menu-2">
    <nav role="navigation" class="navigation-items w-nav-menu"><a href="#" class="navigation-item-2 w-nav-link">Learn</a><a href="#" class="navigation-item-2 w-nav-link">Mon frigo</a><a href="#" class="navigation-item-2 w-nav-link">All</a></nav>
    <div class="menu-button w-nav-button">
    <img src="<%= image_path "menu-icon_1menu-icon.png" %>"  width="22" alt="menu icon" class="menu-icon"></div>
  </div>
  <a href="mailto:mail@business.com?subject=You&#x27;ve%20got%20mail!" class="button cc-contact-us w-inline-block">
    <div>Connexion</div>
  </a>
</div>
</div>
<div class="menu-box"><a href="#" class="menu-item w-button"><strong></strong> </a><a href="#" class="menu-item active w-button"><strong></strong></a><a href="#" class="menu-item w-button"><strong></strong></a></div>
<div class="banner">
<div class="container w-container">
  <div class="h1">Become a cocktail&#x27;s <strong class="bold-text-4">Master</strong></div>
  <div class="subtitle"><a href="#" class="action w-button">Connexion</a></div>
</div>
</div>
<div class="container-3 w-container">
<div class="div-block-5"><a href="#" class="action w-button frigo-btn">Rechercher avec mes ingrédients</a></div>
<div class="search-box">
  <div class="form-block w-form">
  <%= form_tag cocktails_path, method: :get do %>
    <%= text_field_tag :query,
    params[:query], class: "search-field", placeholder: "Rechercher"%>
    <button type="submit" class="search-button"><i class="fa fa-search"> </i></button>
  <% end %>
    <div class="w-form-done">
      <div>Thank you! Your submission has been received!</div>
    </div>
    <div class="w-form-fail">
      <div>Oops! Something went wrong while submitting the form.</div>
    </div>
  </div>
</div>
<div class="result">
  <div class="text-block-3">Liste des cocktails</div><a href="#" data-w-id="0d74062c-e2c4-fd4b-0c0d-58fcde32905e" class="add-btn w-button"><strong class="bold-text"></strong></a></div>
<div class="w-layout-grid grid">


  <% @cocktails.each do |item| %>
   
    <div id=<%="card_"+item.id.to_s%> class="cocktail-card" style="background-image : linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),  url( <%= item.photo.present? ? item.photo : cl_image_path("vucs2ncsgrk6eo0iho2g") %>); background-size: cover;">

      <div class="card-cocktail-header">
      <div class="text-block-7">100%</div>
      <a href="#" class="button-2 w-button"><strong></strong></a></div>
      <div class="card-inner-cocktail">
        <div class="text-block-2" style="height: 80%"><%= item.name %></div>
      </div>
      <div class="card-footer hidden"></div>
    </div>


    <div id=<%="modal_"+item.id.to_s%> class="modal">
<div class="modal-header"><a data-w-id="c9b0a6de-14b6-d1c7-bce1-8201d9bb9d3e" href="#" class="close w-button"></a></div>
<div class="modal-inner">
  <div class="colone">
    <div class="cocktail-card show" style="background-image : linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),  url( <%= item.photo.present? ? item.photo : cl_image_path("vucs2ncsgrk6eo0iho2g") %>); background-size: cover;">
      <div class="card-cocktail-header"><a href="#" class="button-2 w-button"><strong></strong></a></div>
      <div class="card-inner-cocktail">
        <div class="text-block-2"><%=item.name%></div>
      </div>
      <div class="card-footer"></div>
    </div>
    <div class="card _100">
      <div class="card-header">
        <div class="text-block-4">Ingrédients</div>
      </div>
      <div class="card-inner">

       <% item.doses.each do |item| %>
          <div class="ig-list">
            <div class="text-block-6"><%= item.description%></div>
            <div class="text-block-5"></div>
          </div>
        <%end%>
    
      </div>
    </div>
  </div>
  <div class="card description">
    <div class="card-header">
      <div class="text-block-4">Description</div>
    </div>
    <div class="card-inner-cocktail">
    <%= simple_format(item.description) %>
    <br></div>
  </div>
</div>
</div>

  <%end%>


 


</div>
</div>

<div id="modal_frigo" class="modal frigo">
<div class="modal-header">
  <div class="text-block-9">Mes ingrédients</div><a data-w-id="59a80e03-2a8c-50bb-a8de-08fce2e057de" href="#" class="close w-button"></a></div>
<div class="modal-inner">
  <div class="colone">
    <div class="card _100">
      <div class="card-inner">
      <%= form_tag cocktails_path, method: :get do %>
        <%= select('get', :ig , Ingredient.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, class: 'select2', multiple: 'multiple', data: { placeholder: "Ajouter un ingrédient" }) %>
        <hr>
        <%= submit_tag "Recherche", class: "btn btn-primary" %>
    <% end %>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Grecocktail</title>

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable"  content="yes">
    <%= csrf_meta_tags %>
    <%= render 'shared/ios_pwa_links' %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">

  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%#= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

 

    <%= yield %>

    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.4.1.min.220afd743d.js" type="text/javascript" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
<%= link_to "/test", class: "navbar-brand" do %>
  <%= icon('fas', 'cocktail') %>
  Grecocktails
<% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span> 
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
     
      <li class="nav-item">
      <div class="search-bar <%= action_name %>">
        <%= form_tag cocktails_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query], class: "search-field", placeholder: "Rechercher"%>
          <button type="submit" class="search-button"><i class="fa fa-search"> </i></button>
        <% end %>
      </div>
      <li class="nav-item">
      <%= link_to "Learn", '/learn', class: "nav-link" %>
    </li>
      </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Learn", '/learn', class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>